{application,nitrogen,
             [{description,"My Nitrogen Web Project"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{nitrogen_app,[]}},
              {env,[]},
              {modules,[common,db,index,login,nitrogen_app,nitrogen_init,
                        nitrogen_sup,nitrogen_webmachine,signup,
                        static_resource,static_route_handler,verify]}]}.
